# Generated by Django 4.2.25 on 2025-10-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_remove_accommodation_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
    ]
