# Generated by Django 4.2.25 on 2025-10-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_percent', models.PositiveIntegerField(help_text='Discount percentage (e.g. 10 for 10%)')),
            ],
        ),
    ]
