# Generated by Django 4.2.25 on 2025-10-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_festivaldiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accommodation.festivaldiscount'),
        ),
        migrations.AddField(
            model_name='festivaldiscount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
