# Generated by Django 4.2.25 on 2025-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_accommodation_discount_festivaldiscount_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='discount',
            new_name='festival_discount',
        ),
        migrations.RemoveField(
            model_name='festivaldiscount',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='festivaldiscount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (e.g. 10.00 for 10%)', max_digits=5),
            preserve_default=False,
        ),
    ]
