# Generated by Django 4.2.25 on 2025-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_rename_discount_accommodation_festival_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
