# Generated by Django 4.2.7 on 2025-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_booking_discount_applied_booking_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivaldiscount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
